[package]
name = "using_tracing"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = { version = "0.10.1", features = ["thread_rng"] }
tracing = "0.1"

#tracing-subscriber = "0.3"
# If we wanted to set the log level in our code instead of using an environment variable, we could do that by configuring our subscriber.
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
uuid = { version = "1.23.3", features = [ "v4" ] }
